// Code generated by ecal/stdlib/generate; DO NOT EDIT.

package stdlib

import (
	"fmt"
	"math"
	"reflect"
)

/*
genStdlib contains all generated stdlib constructs.
*/
var genStdlib = map[interface{}]interface{}{
	"math-synopsis": "Mathematics-related constants and functions",
	"math-const":    mathConstMap,
	"math-func":     mathFuncMap,
	"math-func-doc": mathFuncDocMap,
}

/*
mathConstMap contains the mapping of stdlib math constants.
*/
var mathConstMap = map[interface{}]interface{}{
	"E":   float64(math.E),
	"Phi": float64(math.Phi),
	"Pi":  float64(math.Pi),
}

/*
mathFuncDocMap contains the documentation of stdlib math functions.
*/
var mathFuncDocMap = map[interface{}]interface{}{
	"inf":   "Function: inf",
	"isInf": "Function: isInf",
	"isNaN": "Function: isNaN",
}

/*
mathFuncMap contains the mapping of stdlib math functions.
*/
var mathFuncMap = map[interface{}]interface{}{
	"inf":   &ECALFunctionAdapter{reflect.ValueOf(math.Inf), fmt.Sprint(mathFuncDocMap["inf"])},
	"isInf": &ECALFunctionAdapter{reflect.ValueOf(math.IsInf), fmt.Sprint(mathFuncDocMap["isInf"])},
	"isNaN": &ECALFunctionAdapter{reflect.ValueOf(math.IsNaN), fmt.Sprint(mathFuncDocMap["isNaN"])},
}

// Dummy statement to prevent declared and not used errors
var Dummy = fmt.Sprint(reflect.ValueOf(fmt.Sprint))
